#This is basic workflow tolearn GitActions

name: StrongDMGatewayDeRegister

on: [push]

Workflow_dispatch:

jobs:

  build:
  translations:
  runs-on: ubuntu-latest
  environment: PRD 

  steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Install Jq
      run: sudo apt-get install -y jq
    
    - name: Install Azure CLI
      run: |
          sudo apt-get install ca-certificates curl apt-transport-https lsb-release gnupg
          curl -sL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/microsoft.gpg > /dev/null
          AZ_REPO=$(lsb_release -cs)
          echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" | sudo tee /etc/apt/sources.list.d/azure-cli.list
          sudo apt-get update
          sudo apt-get install azure-cli
          
    - name: Azure Login
      run: |
         az login --service-principal -u ${{env.AZURE_CLIENT_ID}} -p ${{env.AZURE_CLIENT_SECRET}} --tenant ${{env.AZURE_TENANT_ID}}
         az account set --subscription ${{env.AZURE_SUBSCRIPTION_ID}}

    - name: curl
       uses: wei/curl@master
       with: 
       args: 
       HOSTNAME=`curl --write-out '%{http://169.254.169.254/metadata/instance?api-version=2017-08-01" | jq -r '.compute | .name}'`



      
