#This is basic workflow tolearn GitActions

name: StrongDMGatewayDeRegister

on: [push]
jobs:
  translations:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Install Jq
      run: sudo apt-get install -y jq
    - name: curl
      uses: wei/curl@master
      with:
       args: http://169.254.169.254/metadata/instance?api-version=2017-08-01" | jq -r '.compute | .name'
    
    - name: Install Azure CLI
      run: |
        echo -e "[azure-cli]
        name=Azure CLI
        baseurl=https://packages.microsoft.com/yumrepos/azure-cli
        enabled=1
        gpgcheck=1
        gpgkey=https://packages.microsoft.com/keys/microsoft.asc" | sudo tee /etc/yum.repos.d/azure-cli.repo
        sudo dnf install -y azure-cli 
         
      
