#This is basic workflow tolearn GitActions

name: StrongDMGatewayDeRegister

on:

 push:

 workflow_dispatch:

jobs:

 build:
  
  runs-on: ubuntu-latest
  
  environment: PRD 

  steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Install Jq
      run: sudo apt-get install -y jq
    
    - name: Install Azure CLI
      run: |
          sudo apt-get install ca-certificates curl apt-transport-https lsb-release gnupg
          curl -sL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/microsoft.gpg > /dev/null
          AZ_REPO=$(lsb_release -cs)
          echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" | sudo tee /etc/apt/sources.list.d/azure-cli.list
          sudo apt-get update
          sudo apt-get install azure-cli
          
    - name: Azure Login
      run: |
         echo "Generating Token"
         az login -u SNEMISHRA@DELOITT.COM -p Myloveisfor@4428
     

    

      
